sudo: false
language: node_js
node_js:
  - "5"

cache:
  directories:
    - node_modules

install:
  - npm install

script:
  - npm run lint
  - npm run flow:check
  # - npm run test
  - NODE_ENV=development npm run deploy
  - NODE_ENV=staging npm run deploy
  - NODE_ENV=production npm run deploy

after_success:
  - npm run codecov

deploy:
  provider: heroku
  api_key:
    secure: u5L0BP1vDFzFToAlcdHOeC7PrOnAib3AKgsUvvjNtq3QFsByftaprtLXi9NjeR8xo2G+CDWcaw2TM/7Bvcn1le37szj9HCanpNuuTYn/bP4VR1u4Dkbud5x4ejQJ6xe3/264hxo8n4aQoGIgJvlNxi7JhDL+yuBCL3FW5LEX6JyHnF8vr3+hxzwimvi4Fy/1ITNQpJIdi5CnF/vozByq78TGKfUVBpVXCK3vLmgEp+dpfmuunGrlFd3qaspYcp37zNTaASjp41HvuEe3TE0lOSTZvoRvW7+2oTK5+9ZKJI8RQKxuHYcEXV/JeadzfjGdx8yKpMIj6IYdVKkNXlfOC+Ti+Weh35B/6CYeHwnFM5d9dVPFV4TyVII7r9HoMyxi0kak/WvldnqBppuH/OJNmbVwmv4cSLDVbD708+im4O1Wq9MMXl2wBHbvVY690sg0gppB4D6Ha0A+VARURuSWRI+RBuqRqg13Yl4C/3/rbHXJUAUQYCcMoRM1NXrE3xbF+rcv3p/ypqW5Z1EvCLo+C99qh5ZETuo/PFavUgmY87NpOItIMZe6Ac/T7wjw2rfqCZsPZBZzydkXgaZfKRM87Y91jTJXAK5eX8FA2SIEZb6g27O4LP5OvI4VgHEVtSB6YH8lRjmjnxikrJcPqzqNcMnxXRYQh8qeM3QQBB07jE0=
  app: aichi
  on:
    repo: owenyang0/aichiAdmin
